### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by BluSyn** [bcoin-org/bcurl#4]
If a `request` call in bcurl fails, the error is not properly caught, resulting in `UnhandledPromiseRejectionWarning`.

Simple test case:
```
const {Client} = require('bcurl');
(new Client()).get('/');
```

Result:
```
(node:13878) UnhandledPromiseRejectionWarning: Error: Bad response (wrong content-type).
    at Client.request (<node_modules>/bcurl/lib/client.js:194:13)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:13878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Couldn't find a simple solution that didn't require a ton of try/catch blocks around every request. Perhaps @chjj has a simpler solution.

This was discovered while using `bclient`, which doesn't properly pass request failures back to the original caller. Possible bclient may also need to be updated to properly handle request errors.

**Comment by BluSyn** [comment]
As mentioned above, using a try/catch does work, and seems this is the intended usage:
```
const {Client} = require('bcurl');
(async () => {
  try {
    await (new Client()).get('/');
  } catch(e) { console.error('failed'); }
})()
```

I now realize what I need is a generic error handler in `bclient`, since anything that makes multiple `bclient` calls will need a try/catch around each call to handle request failures. This gets tedious in complex use cases.

Closing this issue since it's actually a `bclient` feature request, not a `bcurl` issue.
